### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by edvasqueza** [taoyuan/slu-seed#1]
Hi, I followed the instructions but I'm getting a command not found error. Am I doing something wrong or is it a bug? the npm install is completing without errors. Thanks.

**Comment by taoyuan** [comment]
My mistake. I will update the document to make more clear for this.

`slu-seed` is a module for [slu](https://github.com/taoyuan/slu). So first you should install `slu`.

``` sh
npm i slu -g
```

And then you can follow the steps in README.md

Let me known if that works.

**Comment by taoyuan** [comment]
It seams that is not active. Close it. Reopen if this is still exists.
